// 100%
const PERFECT_SCORE_MESSAGES = [
  "👑 Perfect score! Outstanding performance today.",
  "🏆 Every answer is correct. Brilliant work!",
  "🥇 Full marks achieved! Congratulations.",
  "💯 Excellent accuracy from start to finish.",
  "🌟 You completed everything perfectly.",
  "🚀 Amazing work! A flawless performance.",
  "✨ Perfect effort, perfect result.",
  "🎉 Fantastic achievement! Full score earned.",
  "📚 Your hard work has paid off beautifully.",
  "🎯 Accuracy at its best. Well done!",
  "💎 A perfect score is a perfect reward.",
  "🧠 Excellent thinking and outstanding execution.",
  "🏅 You gave your best and achieved success.",
  "📖 Every step was completed correctly.",
  "🌈 A wonderful result to be proud of.",
  "🔥 You were focused and it shows.",
  "🍀 Success follows consistent effort.",
  "📘 Full score unlocked! Great job.",
  "🎊 What an impressive performance today!",
  "☀️ Keep shining with results like this.",
  "🦋 Perfect work deserves special recognition.",
  "📈 Your progress continues to impress.",
  "🎨 A beautiful result created by hard work.",
  "👏 Outstanding job on achieving full marks.",
  "🚩 You reached today's goal perfectly.",
  "🏹 Sharp focus brought a perfect result.",
  "🎵 Great learning leads to great achievements.",
  "📗 Another step towards excellence.",
  "⭐ A perfect score is something to celebrate.",
  "👑 Congratulations on your outstanding full score!",
];

// 90%–99%)
const EXCELLENT_SCORE_MESSAGES = [
  "🏆 Excellent work! You're very close to a perfect score.",
  "🌟 Amazing performance today. Keep it up!",
  "🚀 Great effort! You're moving towards perfection.",
  "💎 Outstanding work with excellent accuracy.",
  "🎯 So close to full marks. Well done!",
  "📚 Your hard work is clearly visible.",
  "✨ Fantastic result! Keep aiming high.",
  "🧠 Excellent thinking and strong performance.",
  "🏅 Great job! You're doing very well.",
  "🎉 Wonderful effort and impressive results.",
  "📖 A strong performance to be proud of.",
  "🌈 You're making excellent progress.",
  "🔥 Keep up this fantastic momentum.",
  "🍀 Great accuracy! Keep moving forward.",
  "📘 Outstanding effort with a great score.",
  "🎊 You're getting closer and closer to perfection.",
  "☀️ Keep shining with results like these.",
  "🦋 Excellent work! Your dedication shows.",
  "📈 Your learning journey is moving beautifully.",
  "🎨 Another excellent achievement unlocked.",
  "👏 Fantastic performance! Well done.",
  "🚩 You are setting a great standard.",
  "🏹 Great focus led to a great result.",
  "🎵 Keep learning and keep improving.",
  "📗 A wonderful score achieved through effort.",
  "⭐ Excellent performance! Keep challenging yourself.",
  "💡 Small improvements lead to big achievements.",
  "🌠 Your consistency is bringing success.",
  "🎯 Keep going! You're almost at the top.",
  "🏆 Superb work! Another excellent score achieved.",
];

// 80%–89%)
const MEDIUM_SCORE_MESSAGE = [
  "✨ Very good work! Keep up the great effort.",
  "📚 Nice performance today. Keep moving forward.",
  "🌟 You're making strong progress. Well done!",
  "🚀 Great job! Keep aiming even higher.",
  "🎯 A very good score earned through effort.",
  "🏅 Well done! Your practice is showing results.",
  "📖 Keep learning and keep growing.",
  "💡 Good work! Every step counts.",
  "🎉 A wonderful effort today. Congratulations!",
  "🌈 You're improving beautifully. Keep it up.",
  "📘 Great performance! Stay focused.",
  "🧠 Your hard work is helping you improve.",
  "🍀 Keep believing in yourself and your abilities.",
  "🔥 Nice work! Keep the momentum going.",
  "📈 Good progress deserves appreciation.",
  "🎊 You're on the right path to success.",
  "☀️ Keep shining through your efforts.",
  "🦋 Great learning happens through regular practice.",
  "🎨 Wonderful effort! Keep achieving more.",
  "👏 A strong performance today. Well done!",
  "🚩 Keep moving ahead with confidence.",
  "🏹 Focus and practice will take you further.",
  "🎵 Learning becomes easier with consistency.",
  "📗 Great work! Keep building your skills.",
  "⭐ You're doing well. Keep aiming higher.",
  "💎 Your effort is making a positive difference.",
  "🌱 Every practice session helps you grow.",
  "📒 Keep working hard and success will follow.",
  "🌠 You're getting stronger with every attempt.",
  "✨ Excellent effort! Keep reaching for new goals.",
];

// 70%–79%
const LOW_SCORE_MESSAGE = [
  "👍 Good job! Keep practicing and you'll improve even more.",
  "📚 Nice effort today. Keep moving forward.",
  "🌱 Every practice helps you grow stronger.",
  "💡 You're learning new things every day. Keep it up!",
  "⭐ Good work! Keep believing in yourself.",
  "🚀 You're making progress. Keep going!",
  "📝 A good effort today. Keep building your skills.",
  "🌟 Keep practicing and great results will follow.",
  "🎯 You're on the right path. Stay focused.",
  "📖 Learning takes time. Keep up the effort.",
  "🍀 Good work today! Keep trying your best.",
  "🔥 Your effort matters. Keep moving forward.",
  "📘 Nice job! Practice will make you even stronger.",
  "🎉 Every step forward is a success.",
  "🧠 Keep learning and keep growing.",
  "🌈 Great effort! Brighter results are ahead.",
  "📈 You're improving little by little. Well done!",
  "🎊 Good progress! Keep the momentum going.",
  "☀️ Stay positive and keep working hard.",
  "🦋 Every attempt helps you become better.",
  "🎨 Good work! Keep exploring and learning.",
  "👏 Nice effort today. Keep aiming higher.",
  "🚩 Stay consistent and success will follow.",
  "🏹 Focus and practice will help you improve.",
  "🎵 Keep learning with confidence and enthusiasm.",
  "📗 Good job! Your hard work is important.",
  "💎 Every improvement is something to celebrate.",
  "🌠 Keep trying, keep learning, keep growing.",
  "📒 You're making progress. Keep it up!",
  "👍 Good effort today! Tomorrow is another chance to shine.",
];

// below 70%
const SUPER_LOW_MESSAGE = [
  "🚀 Keep going! Every effort brings improvement.",
  "🌱 Don't worry, you're still learning and growing.",
  "💡 Mistakes help you learn better next time.",
  "⭐ Believe in yourself and try again.",
  "📚 Keep practicing and you'll improve.",
  "🌈 Every try makes you stronger.",
  "🧠 Learning takes time. Keep it up!",
  "🔥 Don't give up. You're on the right path.",
  "📖 Keep working, success will come step by step.",
  "🌟 Small progress is still progress.",
  "🎯 Focus on improving little by little.",
  "🍀 You can do better next time. Keep trying.",
  "📘 Keep practicing regularly for better results.",
  "🦋 Every mistake is a learning step.",
  "☀️ Stay positive and keep learning.",
  "🎉 Keep your confidence strong.",
  "📈 Improvement will come with practice.",
  "🎊 Don't lose hope. Keep moving forward.",
  "🏅 Every effort counts. Keep going.",
  "🚩 Try again with more focus.",
  "🏹 Keep aiming higher every day.",
  "🎵 Learning becomes better with practice.",
  "📗 You're still improving. Keep it up.",
  "💎 Your effort is important. Don't stop.",
  "🌠 Better results are coming soon.",
  "👏 Keep trying your best every day.",
  "📒 Stay consistent and you'll improve.",
  "🌱 Growth takes time. Keep learning.",
  "⭐ You are capable of doing better.",
  "🚀 Don't stop now. Your progress will come.",
];

module.exports = {
  PERFECT_SCORE_MESSAGES,
  EXCELLENT_SCORE_MESSAGES,
  MEDIUM_SCORE_MESSAGE,
  LOW_SCORE_MESSAGE,
  SUPER_LOW_MESSAGE,
};
