name: Keep Render Alive
on:
  schedule:
    - cron: '*/12 0-17 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -f https://jjwingabackend.onrender.com/v1/api/health || exit 0